//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viajes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public int IdCliente { get; set; }
        public int IdViaje { get; set; }
        public System.DateTime FechaReserva { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Viajes Viajes { get; set; }
    }
}
